//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum BookableResourceBookingHeaderState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reservation entity representing the summary of the associated resource bookings.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bookableresourcebookingheader")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class BookableResourceBookingHeader : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string BookableResourceBookingHeaderId = "bookableresourcebookingheaderid";
			public const string Id = "bookableresourcebookingheaderid";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Duration = "duration";
			public const string EndTime = "endtime";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Name = "name";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ProcessId = "processid";
			public const string StageId = "stageid";
			public const string StartTime = "starttime";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TraversedPath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_bookableresourcebookingheader = "business_unit_bookableresourcebookingheader";
			public const string lk_bookableresourcebookingheader_createdby = "lk_bookableresourcebookingheader_createdby";
			public const string lk_bookableresourcebookingheader_createdonbehalfby = "lk_bookableresourcebookingheader_createdonbehalfby";
			public const string lk_bookableresourcebookingheader_modifiedby = "lk_bookableresourcebookingheader_modifiedby";
			public const string lk_bookableresourcebookingheader_modifiedonbehalfby = "lk_bookableresourcebookingheader_modifiedonbehalfby";
			public const string processstage_BookableResourceBookingHeader = "processstage_BookableResourceBookingHeader";
			public const string team_bookableresourcebookingheader = "team_bookableresourcebookingheader";
			public const string TransactionCurrency_bookableresourcebookingheader = "TransactionCurrency_bookableresourcebookingheader";
			public const string user_bookableresourcebookingheader = "user_bookableresourcebookingheader";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceBookingHeader() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bookableresourcebookingheader";
		
		public const string PrimaryIdAttribute = "bookableresourcebookingheaderid";
		
		public const string PrimaryNameAttribute = "name";
		
		public const int EntityTypeCode = 1146;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the resource booking header.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcebookingheaderid")]
		public System.Nullable<System.Guid> BookableResourceBookingHeaderId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bookableresourcebookingheaderid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookableResourceBookingHeaderId");
				this.SetAttributeValue("bookableresourcebookingheaderid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("BookableResourceBookingHeaderId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcebookingheaderid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.BookableResourceBookingHeaderId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the aggregate duration of the linked bookings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duration")]
		public System.Nullable<int> Duration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("duration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Duration");
				this.SetAttributeValue("duration", value);
				this.OnPropertyChanged("Duration");
			}
		}
		
		/// <summary>
		/// Shows the end date and time of the booking summary.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("endtime")]
		public System.Nullable<System.DateTime> EndTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("endtime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EndTime");
				this.SetAttributeValue("endtime", value);
				this.OnPropertyChanged("EndTime");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the bookableresourcebookingheader with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// The name of the booking summary.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProcessId");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("ProcessId");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StageId");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("StageId");
			}
		}
		
		/// <summary>
		/// Shows the start date and time of the booking summary.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("starttime")]
		public System.Nullable<System.DateTime> StartTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("starttime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StartTime");
				this.SetAttributeValue("starttime", value);
				this.OnPropertyChanged("StartTime");
			}
		}
		
		/// <summary>
		/// Status of the Bookable Resource Booking Header
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Common.Entities.BookableResourceBookingHeaderState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Common.Entities.BookableResourceBookingHeaderState)(System.Enum.ToObject(typeof(Common.Entities.BookableResourceBookingHeaderState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Bookable Resource Booking Header
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the BookableResourceBookingHeader with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TraversedPath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("TraversedPath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<Common.Entities.ActivityPointer> bookableresourcebookingheader_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.ActivityPointer>("bookableresourcebookingheader_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_ActivityPointers");
				this.SetRelatedEntities<Common.Entities.ActivityPointer>("bookableresourcebookingheader_ActivityPointers", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_Annotations")]
		public System.Collections.Generic.IEnumerable<Common.Entities.Annotation> bookableresourcebookingheader_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.Annotation>("bookableresourcebookingheader_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_Annotations");
				this.SetRelatedEntities<Common.Entities.Annotation>("bookableresourcebookingheader_Annotations", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_Appointments")]
		public System.Collections.Generic.IEnumerable<Common.Entities.Appointment> bookableresourcebookingheader_Appointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.Appointment>("bookableresourcebookingheader_Appointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_Appointments");
				this.SetRelatedEntities<Common.Entities.Appointment>("bookableresourcebookingheader_Appointments", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Common.Entities.AsyncOperation> bookableresourcebookingheader_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.AsyncOperation>("bookableresourcebookingheader_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_AsyncOperations");
				this.SetRelatedEntities<Common.Entities.AsyncOperation>("bookableresourcebookingheader_AsyncOperations", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_bookableresourcebooking_Header
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_bookableresourcebooking_Header")]
		public System.Collections.Generic.IEnumerable<Common.Entities.BookableResourceBooking> bookableresourcebookingheader_bookableresourcebooking_Header
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.BookableResourceBooking>("bookableresourcebookingheader_bookableresourcebooking_Header", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_bookableresourcebooking_Header");
				this.SetRelatedEntities<Common.Entities.BookableResourceBooking>("bookableresourcebookingheader_bookableresourcebooking_Header", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_bookableresourcebooking_Header");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<Common.Entities.BulkDeleteFailure> bookableresourcebookingheader_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.BulkDeleteFailure>("bookableresourcebookingheader_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_BulkDeleteFailures");
				this.SetRelatedEntities<Common.Entities.BulkDeleteFailure>("bookableresourcebookingheader_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_BulkOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_BulkOperations")]
		public System.Collections.Generic.IEnumerable<Common.Entities.BulkOperation> bookableresourcebookingheader_BulkOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.BulkOperation>("bookableresourcebookingheader_BulkOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_BulkOperations");
				this.SetRelatedEntities<Common.Entities.BulkOperation>("bookableresourcebookingheader_BulkOperations", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_BulkOperations");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_CampaignActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_CampaignActivities")]
		public System.Collections.Generic.IEnumerable<Common.Entities.CampaignActivity> bookableresourcebookingheader_CampaignActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.CampaignActivity>("bookableresourcebookingheader_CampaignActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_CampaignActivities");
				this.SetRelatedEntities<Common.Entities.CampaignActivity>("bookableresourcebookingheader_CampaignActivities", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_CampaignActivities");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_CampaignResponses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_CampaignResponses")]
		public System.Collections.Generic.IEnumerable<Common.Entities.CampaignResponse> bookableresourcebookingheader_CampaignResponses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.CampaignResponse>("bookableresourcebookingheader_CampaignResponses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_CampaignResponses");
				this.SetRelatedEntities<Common.Entities.CampaignResponse>("bookableresourcebookingheader_CampaignResponses", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_CampaignResponses");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Common.Entities.DuplicateRecord> bookableresourcebookingheader_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.DuplicateRecord>("bookableresourcebookingheader_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_DuplicateBaseRecord");
				this.SetRelatedEntities<Common.Entities.DuplicateRecord>("bookableresourcebookingheader_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Common.Entities.DuplicateRecord> bookableresourcebookingheader_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.DuplicateRecord>("bookableresourcebookingheader_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_DuplicateMatchingRecord");
				this.SetRelatedEntities<Common.Entities.DuplicateRecord>("bookableresourcebookingheader_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_Emails")]
		public System.Collections.Generic.IEnumerable<Common.Entities.Email> bookableresourcebookingheader_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.Email>("bookableresourcebookingheader_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_Emails");
				this.SetRelatedEntities<Common.Entities.Email>("bookableresourcebookingheader_Emails", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_Emails");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_Faxes")]
		public System.Collections.Generic.IEnumerable<Common.Entities.Fax> bookableresourcebookingheader_Faxes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.Fax>("bookableresourcebookingheader_Faxes", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_Faxes");
				this.SetRelatedEntities<Common.Entities.Fax>("bookableresourcebookingheader_Faxes", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_IncidentResolutions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_IncidentResolutions")]
		public System.Collections.Generic.IEnumerable<Common.Entities.IncidentResolution> bookableresourcebookingheader_IncidentResolutions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.IncidentResolution>("bookableresourcebookingheader_IncidentResolutions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_IncidentResolutions");
				this.SetRelatedEntities<Common.Entities.IncidentResolution>("bookableresourcebookingheader_IncidentResolutions", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_IncidentResolutions");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_Letters")]
		public System.Collections.Generic.IEnumerable<Common.Entities.Letter> bookableresourcebookingheader_Letters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.Letter>("bookableresourcebookingheader_Letters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_Letters");
				this.SetRelatedEntities<Common.Entities.Letter>("bookableresourcebookingheader_Letters", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_Letters");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<Common.Entities.MailboxTrackingFolder> bookableresourcebookingheader_MailboxTrackingFolders
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.MailboxTrackingFolder>("bookableresourcebookingheader_MailboxTrackingFolders", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_MailboxTrackingFolders");
				this.SetRelatedEntities<Common.Entities.MailboxTrackingFolder>("bookableresourcebookingheader_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_OpportunityCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_OpportunityCloses")]
		public System.Collections.Generic.IEnumerable<Common.Entities.OpportunityClose> bookableresourcebookingheader_OpportunityCloses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.OpportunityClose>("bookableresourcebookingheader_OpportunityCloses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_OpportunityCloses");
				this.SetRelatedEntities<Common.Entities.OpportunityClose>("bookableresourcebookingheader_OpportunityCloses", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_OpportunityCloses");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_OrderCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_OrderCloses")]
		public System.Collections.Generic.IEnumerable<Common.Entities.OrderClose> bookableresourcebookingheader_OrderCloses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.OrderClose>("bookableresourcebookingheader_OrderCloses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_OrderCloses");
				this.SetRelatedEntities<Common.Entities.OrderClose>("bookableresourcebookingheader_OrderCloses", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_OrderCloses");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<Common.Entities.PhoneCall> bookableresourcebookingheader_PhoneCalls
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.PhoneCall>("bookableresourcebookingheader_PhoneCalls", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_PhoneCalls");
				this.SetRelatedEntities<Common.Entities.PhoneCall>("bookableresourcebookingheader_PhoneCalls", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_PrincipalObjectAttributeAccess
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_PrincipalObjectAttributeAccess")]
		public System.Collections.Generic.IEnumerable<Common.Entities.PrincipalObjectAttributeAccess> bookableresourcebookingheader_PrincipalObjectAttributeAccess
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.PrincipalObjectAttributeAccess>("bookableresourcebookingheader_PrincipalObjectAttributeAccess", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_PrincipalObjectAttributeAccess");
				this.SetRelatedEntities<Common.Entities.PrincipalObjectAttributeAccess>("bookableresourcebookingheader_PrincipalObjectAttributeAccess", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_PrincipalObjectAttributeAccess");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_ProcessSession")]
		public System.Collections.Generic.IEnumerable<Common.Entities.ProcessSession> bookableresourcebookingheader_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.ProcessSession>("bookableresourcebookingheader_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_ProcessSession");
				this.SetRelatedEntities<Common.Entities.ProcessSession>("bookableresourcebookingheader_ProcessSession", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_QuoteCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_QuoteCloses")]
		public System.Collections.Generic.IEnumerable<Common.Entities.QuoteClose> bookableresourcebookingheader_QuoteCloses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.QuoteClose>("bookableresourcebookingheader_QuoteCloses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_QuoteCloses");
				this.SetRelatedEntities<Common.Entities.QuoteClose>("bookableresourcebookingheader_QuoteCloses", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_QuoteCloses");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<Common.Entities.RecurringAppointmentMaster> bookableresourcebookingheader_RecurringAppointmentMasters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.RecurringAppointmentMaster>("bookableresourcebookingheader_RecurringAppointmentMasters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_RecurringAppointmentMasters");
				this.SetRelatedEntities<Common.Entities.RecurringAppointmentMaster>("bookableresourcebookingheader_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<Common.Entities.ServiceAppointment> bookableresourcebookingheader_ServiceAppointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.ServiceAppointment>("bookableresourcebookingheader_ServiceAppointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_ServiceAppointments");
				this.SetRelatedEntities<Common.Entities.ServiceAppointment>("bookableresourcebookingheader_ServiceAppointments", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_SocialActivities")]
		public System.Collections.Generic.IEnumerable<Common.Entities.SocialActivity> bookableresourcebookingheader_SocialActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.SocialActivity>("bookableresourcebookingheader_SocialActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_SocialActivities");
				this.SetRelatedEntities<Common.Entities.SocialActivity>("bookableresourcebookingheader_SocialActivities", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N BookableResourceBookingHeader_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("BookableResourceBookingHeader_SyncErrors")]
		public System.Collections.Generic.IEnumerable<Common.Entities.SyncError> BookableResourceBookingHeader_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.SyncError>("BookableResourceBookingHeader_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookableResourceBookingHeader_SyncErrors");
				this.SetRelatedEntities<Common.Entities.SyncError>("BookableResourceBookingHeader_SyncErrors", null, value);
				this.OnPropertyChanged("BookableResourceBookingHeader_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_Tasks")]
		public System.Collections.Generic.IEnumerable<Common.Entities.Task> bookableresourcebookingheader_Tasks
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.Task>("bookableresourcebookingheader_Tasks", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_Tasks");
				this.SetRelatedEntities<Common.Entities.Task>("bookableresourcebookingheader_Tasks", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebookingheader_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<Common.Entities.UserEntityInstanceData> bookableresourcebookingheader_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.UserEntityInstanceData>("bookableresourcebookingheader_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_UserEntityInstanceDatas");
				this.SetRelatedEntities<Common.Entities.UserEntityInstanceData>("bookableresourcebookingheader_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_bookableresourcebookingheader
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_bookableresourcebookingheader")]
		public Common.Entities.BusinessUnit business_unit_bookableresourcebookingheader
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BusinessUnit>("business_unit_bookableresourcebookingheader", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebookingheader_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebookingheader_createdby")]
		public Common.Entities.SystemUser lk_bookableresourcebookingheader_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SystemUser>("lk_bookableresourcebookingheader_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebookingheader_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebookingheader_createdonbehalfby")]
		public Common.Entities.SystemUser lk_bookableresourcebookingheader_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SystemUser>("lk_bookableresourcebookingheader_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcebookingheader_createdonbehalfby");
				this.SetRelatedEntity<Common.Entities.SystemUser>("lk_bookableresourcebookingheader_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_bookableresourcebookingheader_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebookingheader_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebookingheader_modifiedby")]
		public Common.Entities.SystemUser lk_bookableresourcebookingheader_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SystemUser>("lk_bookableresourcebookingheader_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebookingheader_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebookingheader_modifiedonbehalfby")]
		public Common.Entities.SystemUser lk_bookableresourcebookingheader_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SystemUser>("lk_bookableresourcebookingheader_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcebookingheader_modifiedonbehalfby");
				this.SetRelatedEntity<Common.Entities.SystemUser>("lk_bookableresourcebookingheader_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_bookableresourcebookingheader_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 processstage_BookableResourceBookingHeader
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("processstage_BookableResourceBookingHeader")]
		public Common.Entities.ProcessStage processstage_BookableResourceBookingHeader
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.ProcessStage>("processstage_BookableResourceBookingHeader", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("processstage_BookableResourceBookingHeader");
				this.SetRelatedEntity<Common.Entities.ProcessStage>("processstage_BookableResourceBookingHeader", null, value);
				this.OnPropertyChanged("processstage_BookableResourceBookingHeader");
			}
		}
		
		/// <summary>
		/// N:1 team_bookableresourcebookingheader
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_bookableresourcebookingheader")]
		public Common.Entities.Team team_bookableresourcebookingheader
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Team>("team_bookableresourcebookingheader", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_bookableresourcebookingheader
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_bookableresourcebookingheader")]
		public Common.Entities.TransactionCurrency TransactionCurrency_bookableresourcebookingheader
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.TransactionCurrency>("TransactionCurrency_bookableresourcebookingheader", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrency_bookableresourcebookingheader");
				this.SetRelatedEntity<Common.Entities.TransactionCurrency>("TransactionCurrency_bookableresourcebookingheader", null, value);
				this.OnPropertyChanged("TransactionCurrency_bookableresourcebookingheader");
			}
		}
		
		/// <summary>
		/// N:1 user_bookableresourcebookingheader
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_bookableresourcebookingheader")]
		public Common.Entities.SystemUser user_bookableresourcebookingheader
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SystemUser>("user_bookableresourcebookingheader", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceBookingHeader(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["bookableresourcebookingheaderid"] = base.Id;
                        break;
                    case "bookableresourcebookingheaderid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual BookableResourceBookingHeader_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((BookableResourceBookingHeader_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}