//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Entities
{
	
	/// <summary>
	/// Potential duplicate record.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("duplicaterecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class DuplicateRecord : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string AsyncOperationId = "asyncoperationid";
			public const string BaseRecordId = "baserecordid";
			public const string CreatedOn = "createdon";
			public const string DuplicateId = "duplicateid";
			public const string Id = "duplicateid";
			public const string DuplicateRecordId = "duplicaterecordid";
			public const string DuplicateRuleId = "duplicateruleid";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningUser = "owninguser";
			public const string Account_DuplicateBaseRecord = "Account_DuplicateBaseRecord";
			public const string Account_DuplicateMatchingRecord = "Account_DuplicateMatchingRecord";
			public const string Appointment_DuplicateBaseRecord = "Appointment_DuplicateBaseRecord";
			public const string Appointment_DuplicateMatchingRecord = "Appointment_DuplicateMatchingRecord";
			public const string AsyncOperation_DuplicateBaseRecord = "AsyncOperation_DuplicateBaseRecord";
			public const string bookableresource_DuplicateBaseRecord = "bookableresource_DuplicateBaseRecord";
			public const string bookableresource_DuplicateMatchingRecord = "bookableresource_DuplicateMatchingRecord";
			public const string bookableresourcebooking_DuplicateBaseRecord = "bookableresourcebooking_DuplicateBaseRecord";
			public const string bookableresourcebooking_DuplicateMatchingRecord = "bookableresourcebooking_DuplicateMatchingRecord";
			public const string bookableresourcebookingheader_DuplicateBaseRecord = "bookableresourcebookingheader_DuplicateBaseRecord";
			public const string bookableresourcebookingheader_DuplicateMatchingRecord = "bookableresourcebookingheader_DuplicateMatchingRecord";
			public const string bookableresourcecategory_DuplicateBaseRecord = "bookableresourcecategory_DuplicateBaseRecord";
			public const string bookableresourcecategory_DuplicateMatchingRecord = "bookableresourcecategory_DuplicateMatchingRecord";
			public const string bookableresourcecategoryassn_DuplicateBaseRecord = "bookableresourcecategoryassn_DuplicateBaseRecord";
			public const string bookableresourcecategoryassn_DuplicateMatchingRecord = "bookableresourcecategoryassn_DuplicateMatchingRecord";
			public const string bookableresourcecharacteristic_DuplicateBaseRecord = "bookableresourcecharacteristic_DuplicateBaseRecord";
			public const string bookableresourcecharacteristic_DuplicateMatchingRecord = "bookableresourcecharacteristic_DuplicateMatchingRecord";
			public const string bookableresourcegroup_DuplicateBaseRecord = "bookableresourcegroup_DuplicateBaseRecord";
			public const string bookableresourcegroup_DuplicateMatchingRecord = "bookableresourcegroup_DuplicateMatchingRecord";
			public const string bookingstatus_DuplicateBaseRecord = "bookingstatus_DuplicateBaseRecord";
			public const string bookingstatus_DuplicateMatchingRecord = "bookingstatus_DuplicateMatchingRecord";
			public const string Campaign_DuplicateBaseRecord = "Campaign_DuplicateBaseRecord";
			public const string Campaign_DuplicateMatchingRecord = "Campaign_DuplicateMatchingRecord";
			public const string CampaignResponse_DuplicateBaseRecord = "CampaignResponse_DuplicateBaseRecord";
			public const string CampaignResponse_DuplicateMatchingRecord = "CampaignResponse_DuplicateMatchingRecord";
			public const string channelaccessprofile_DuplicateBaseRecord = "channelaccessprofile_DuplicateBaseRecord";
			public const string channelaccessprofile_DuplicateMatchingRecord = "channelaccessprofile_DuplicateMatchingRecord";
			public const string characteristic_DuplicateBaseRecord = "characteristic_DuplicateBaseRecord";
			public const string characteristic_DuplicateMatchingRecord = "characteristic_DuplicateMatchingRecord";
			public const string Competitor_DuplicateBaseRecord = "Competitor_DuplicateBaseRecord";
			public const string Competitor_DuplicateMatchingRecord = "Competitor_DuplicateMatchingRecord";
			public const string Contact_DuplicateBaseRecord = "Contact_DuplicateBaseRecord";
			public const string Contact_DuplicateMatchingRecord = "Contact_DuplicateMatchingRecord";
			public const string Contract_DuplicateBaseRecord = "Contract_DuplicateBaseRecord";
			public const string Contract_DuplicateMatchingRecord = "Contract_DuplicateMatchingRecord";
			public const string DuplicateRule_DuplicateBaseRecord = "DuplicateRule_DuplicateBaseRecord";
			public const string Email_DuplicateBaseRecord = "Email_DuplicateBaseRecord";
			public const string Email_DuplicateMatchingRecord = "Email_DuplicateMatchingRecord";
			public const string emailserverprofile_duplicatebaserecord = "emailserverprofile_duplicatebaserecord";
			public const string emailserverprofile_duplicatematchingrecord = "emailserverprofile_duplicatematchingrecord";
			public const string entitlement_DuplicateBaseRecord = "entitlement_DuplicateBaseRecord";
			public const string entitlement_DuplicateMatchingRecord = "entitlement_DuplicateMatchingRecord";
			public const string entitlementchannel_DuplicateBaseRecord = "entitlementchannel_DuplicateBaseRecord";
			public const string entitlementchannel_DuplicateMatchingRecord = "entitlementchannel_DuplicateMatchingRecord";
			public const string entitlementtemplate_DuplicateBaseRecord = "entitlementtemplate_DuplicateBaseRecord";
			public const string entitlementtemplate_DuplicateMatchingRecord = "entitlementtemplate_DuplicateMatchingRecord";
			public const string Equipment_DuplicateBaseRecord = "Equipment_DuplicateBaseRecord";
			public const string Equipment_DuplicateMatchingRecord = "Equipment_DuplicateMatchingRecord";
			public const string Fax_DuplicateBaseRecord = "Fax_DuplicateBaseRecord";
			public const string Fax_DuplicateMatchingRecord = "Fax_DuplicateMatchingRecord";
			public const string Goal_DuplicateBaseRecord = "Goal_DuplicateBaseRecord";
			public const string Goal_DuplicateMatchingRecord = "Goal_DuplicateMatchingRecord";
			public const string GoalRollupQuery_DuplicateBaseRecord = "GoalRollupQuery_DuplicateBaseRecord";
			public const string GoalRollupQuery_DuplicateMatchingRecord = "GoalRollupQuery_DuplicateMatchingRecord";
			public const string Incident_DuplicateBaseRecord = "Incident_DuplicateBaseRecord";
			public const string Incident_DuplicateMatchingRecord = "Incident_DuplicateMatchingRecord";
			public const string KbArticle_DuplicateBaseRecord = "KbArticle_DuplicateBaseRecord";
			public const string KbArticle_DuplicateMatchingRecord = "KbArticle_DuplicateMatchingRecord";
			public const string knowledgearticle_DuplicateBaseRecord = "knowledgearticle_DuplicateBaseRecord";
			public const string knowledgearticle_DuplicateMatchingRecord = "knowledgearticle_DuplicateMatchingRecord";
			public const string KnowledgeBaseRecord_DuplicateBaseRecord = "KnowledgeBaseRecord_DuplicateBaseRecord";
			public const string KnowledgeBaseRecord_DuplicateMatchingRecord = "KnowledgeBaseRecord_DuplicateMatchingRecord";
			public const string Lead_DuplicateBaseRecord = "Lead_DuplicateBaseRecord";
			public const string Lead_DuplicateMatchingRecord = "Lead_DuplicateMatchingRecord";
			public const string Letter_DuplicateBaseRecord = "Letter_DuplicateBaseRecord";
			public const string Letter_DuplicateMatchingRecord = "Letter_DuplicateMatchingRecord";
			public const string List_DuplicateBaseRecord = "List_DuplicateBaseRecord";
			public const string List_DuplicateMatchingRecord = "List_DuplicateMatchingRecord";
			public const string msdyn_postalbum_DuplicateBaseRecord = "msdyn_postalbum_DuplicateBaseRecord";
			public const string msdyn_postalbum_DuplicateMatchingRecord = "msdyn_postalbum_DuplicateMatchingRecord";
			public const string msdyn_relationshipinsightsunifiedconfig_DuplicateBaseRecord = "msdyn_relationshipinsightsunifiedconfig_DuplicateBaseRecord";
			public const string msdyn_relationshipinsightsunifiedconfig_DuplicateMatchingRecord = "msdyn_relationshipinsightsunifiedconfig_DuplicateMatchingRecord";
			public const string msdyn_siconfig_DuplicateBaseRecord = "msdyn_siconfig_DuplicateBaseRecord";
			public const string msdyn_siconfig_DuplicateMatchingRecord = "msdyn_siconfig_DuplicateMatchingRecord";
			public const string Opportunity_DuplicateBaseRecord = "Opportunity_DuplicateBaseRecord";
			public const string Opportunity_DuplicateMatchingRecord = "Opportunity_DuplicateMatchingRecord";
			public const string PhoneCall_DuplicateBaseRecord = "PhoneCall_DuplicateBaseRecord";
			public const string PhoneCall_DuplicateMatchingRecord = "PhoneCall_DuplicateMatchingRecord";
			public const string Publisher_DuplicateBaseRecord = "Publisher_DuplicateBaseRecord";
			public const string Publisher_DuplicateMatchingRecord = "Publisher_DuplicateMatchingRecord";
			public const string Queue_DuplicateBaseRecord = "Queue_DuplicateBaseRecord";
			public const string Queue_DuplicateMatchingRecord = "Queue_DuplicateMatchingRecord";
			public const string Quote_DuplicateBaseRecord = "Quote_DuplicateBaseRecord";
			public const string Quote_DuplicateMatchingRecord = "Quote_DuplicateMatchingRecord";
			public const string ratingmodel_DuplicateBaseRecord = "ratingmodel_DuplicateBaseRecord";
			public const string ratingmodel_DuplicateMatchingRecord = "ratingmodel_DuplicateMatchingRecord";
			public const string ratingvalue_DuplicateBaseRecord = "ratingvalue_DuplicateBaseRecord";
			public const string ratingvalue_DuplicateMatchingRecord = "ratingvalue_DuplicateMatchingRecord";
			public const string RecurringAppointmentMaster_DuplicateBaseRecord = "RecurringAppointmentMaster_DuplicateBaseRecord";
			public const string RecurringAppointmentMaster_DuplicateMatchingRecord = "RecurringAppointmentMaster_DuplicateMatchingRecord";
			public const string ResourceGroup_DuplicateBaseRecord = "ResourceGroup_DuplicateBaseRecord";
			public const string ResourceGroup_DuplicateMatchingRecord = "ResourceGroup_DuplicateMatchingRecord";
			public const string Service_DuplicateBaseRecord = "Service_DuplicateBaseRecord";
			public const string Service_DuplicateMatchingRecord = "Service_DuplicateMatchingRecord";
			public const string SharePointDocumentLocation_DuplicateBaseRecord = "SharePointDocumentLocation_DuplicateBaseRecord";
			public const string SharePointDocumentLocation_DuplicateMatchingRecord = "SharePointDocumentLocation_DuplicateMatchingRecord";
			public const string SharePointSite_DuplicateBaseRecord = "SharePointSite_DuplicateBaseRecord";
			public const string SharePointSite_DuplicateMatchingRecord = "SharePointSite_DuplicateMatchingRecord";
			public const string SocialActivity_DuplicateBaseRecord = "SocialActivity_DuplicateBaseRecord";
			public const string SocialActivity_DuplicateMatchingRecord = "SocialActivity_DuplicateMatchingRecord";
			public const string SocialProfile_DuplicateBaseRecord = "SocialProfile_DuplicateBaseRecord";
			public const string SocialProfile_DuplicateMatchingRecord = "SocialProfile_DuplicateMatchingRecord";
			public const string SystemUser_DuplicateBaseRecord = "SystemUser_DuplicateBaseRecord";
			public const string SystemUser_DuplicateMatchingRecord = "SystemUser_DuplicateMatchingRecord";
			public const string Task_DuplicateBaseRecord = "Task_DuplicateBaseRecord";
			public const string Task_DuplicateMatchingRecord = "Task_DuplicateMatchingRecord";
			public const string Team_DuplicateBaseRecord = "Team_DuplicateBaseRecord";
			public const string Team_DuplicateMatchingRecord = "Team_DuplicateMatchingRecord";
			public const string Territory_DuplicateBaseRecord = "Territory_DuplicateBaseRecord";
			public const string Territory_DuplicateMatchingRecord = "Territory_DuplicateMatchingRecord";
			public const string TransactionCurrency_DuplicateBaseRecord = "TransactionCurrency_DuplicateBaseRecord";
			public const string TransactionCurrency_DuplicateMatchingRecord = "TransactionCurrency_DuplicateMatchingRecord";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public DuplicateRecord() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "duplicaterecord";
		
		public const string PrimaryIdAttribute = "duplicateid";
		
		public const int EntityTypeCode = 4415;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the system job that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asyncoperationid")]
		public Microsoft.Xrm.Sdk.EntityReference AsyncOperationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("asyncoperationid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the base record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		public Microsoft.Xrm.Sdk.EntityReference BaseRecordId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("baserecordid");
			}
		}
		
		/// <summary>
		/// Date and time when the duplicate record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the duplicate record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicateid")]
		public System.Nullable<System.Guid> DuplicateId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("duplicateid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DuplicateId");
				this.SetAttributeValue("duplicateid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("DuplicateId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicateid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.DuplicateId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the potential duplicate record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		public Microsoft.Xrm.Sdk.EntityReference DuplicateRecordId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("duplicaterecordid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the duplicate rule against which this duplicate was found.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicateruleid")]
		public Microsoft.Xrm.Sdk.EntityReference DuplicateRuleId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("duplicateruleid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the duplicate record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit that owns the duplicate record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public System.Nullable<System.Guid> OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the duplicate record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public System.Nullable<System.Guid> OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("owninguser");
			}
		}
		
		/// <summary>
		/// 1:N userentityinstancedata_duplicaterecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_duplicaterecord")]
		public System.Collections.Generic.IEnumerable<Common.Entities.UserEntityInstanceData> userentityinstancedata_duplicaterecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Common.Entities.UserEntityInstanceData>("userentityinstancedata_duplicaterecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("userentityinstancedata_duplicaterecord");
				this.SetRelatedEntities<Common.Entities.UserEntityInstanceData>("userentityinstancedata_duplicaterecord", null, value);
				this.OnPropertyChanged("userentityinstancedata_duplicaterecord");
			}
		}
		
		/// <summary>
		/// N:1 Account_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Account_DuplicateBaseRecord")]
		public Common.Entities.Account Account_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Account>("Account_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Account_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Account_DuplicateMatchingRecord")]
		public Common.Entities.Account Account_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Account>("Account_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Appointment_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Appointment_DuplicateBaseRecord")]
		public Common.Entities.Appointment Appointment_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Appointment>("Appointment_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Appointment_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Appointment_DuplicateMatchingRecord")]
		public Common.Entities.Appointment Appointment_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Appointment>("Appointment_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 AsyncOperation_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asyncoperationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("AsyncOperation_DuplicateBaseRecord")]
		public Common.Entities.AsyncOperation AsyncOperation_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.AsyncOperation>("AsyncOperation_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresource_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresource_DuplicateBaseRecord")]
		public Common.Entities.BookableResource bookableresource_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResource>("bookableresource_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresource_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresource_DuplicateMatchingRecord")]
		public Common.Entities.BookableResource bookableresource_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResource>("bookableresource_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcebooking_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_DuplicateBaseRecord")]
		public Common.Entities.BookableResourceBooking bookableresourcebooking_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceBooking>("bookableresourcebooking_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcebooking_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_DuplicateMatchingRecord")]
		public Common.Entities.BookableResourceBooking bookableresourcebooking_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceBooking>("bookableresourcebooking_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcebookingheader_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_DuplicateBaseRecord")]
		public Common.Entities.BookableResourceBookingHeader bookableresourcebookingheader_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceBookingHeader>("bookableresourcebookingheader_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcebookingheader_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_DuplicateMatchingRecord")]
		public Common.Entities.BookableResourceBookingHeader bookableresourcebookingheader_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceBookingHeader>("bookableresourcebookingheader_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcecategory_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_DuplicateBaseRecord")]
		public Common.Entities.BookableResourceCategory bookableresourcecategory_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceCategory>("bookableresourcecategory_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcecategory_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategory_DuplicateMatchingRecord")]
		public Common.Entities.BookableResourceCategory bookableresourcecategory_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceCategory>("bookableresourcecategory_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcecategoryassn_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategoryassn_DuplicateBaseRecord")]
		public Common.Entities.BookableResourceCategoryAssn bookableresourcecategoryassn_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceCategoryAssn>("bookableresourcecategoryassn_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcecategoryassn_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecategoryassn_DuplicateMatchingRecord")]
		public Common.Entities.BookableResourceCategoryAssn bookableresourcecategoryassn_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceCategoryAssn>("bookableresourcecategoryassn_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcecharacteristic_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecharacteristic_DuplicateBaseRecord")]
		public Common.Entities.BookableResourceCharacteristic bookableresourcecharacteristic_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceCharacteristic>("bookableresourcecharacteristic_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcecharacteristic_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcecharacteristic_DuplicateMatchingRecord")]
		public Common.Entities.BookableResourceCharacteristic bookableresourcecharacteristic_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceCharacteristic>("bookableresourcecharacteristic_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcegroup_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcegroup_DuplicateBaseRecord")]
		public Common.Entities.BookableResourceGroup bookableresourcegroup_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceGroup>("bookableresourcegroup_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcegroup_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcegroup_DuplicateMatchingRecord")]
		public Common.Entities.BookableResourceGroup bookableresourcegroup_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookableResourceGroup>("bookableresourcegroup_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookingstatus_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookingstatus_DuplicateBaseRecord")]
		public Common.Entities.BookingStatus bookingstatus_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookingStatus>("bookingstatus_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 bookingstatus_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookingstatus_DuplicateMatchingRecord")]
		public Common.Entities.BookingStatus bookingstatus_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.BookingStatus>("bookingstatus_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Campaign_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Campaign_DuplicateBaseRecord")]
		public Common.Entities.Campaign Campaign_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Campaign>("Campaign_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Campaign_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Campaign_DuplicateMatchingRecord")]
		public Common.Entities.Campaign Campaign_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Campaign>("Campaign_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 CampaignResponse_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("CampaignResponse_DuplicateBaseRecord")]
		public Common.Entities.CampaignResponse CampaignResponse_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.CampaignResponse>("CampaignResponse_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 CampaignResponse_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("CampaignResponse_DuplicateMatchingRecord")]
		public Common.Entities.CampaignResponse CampaignResponse_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.CampaignResponse>("CampaignResponse_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 channelaccessprofile_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("channelaccessprofile_DuplicateBaseRecord")]
		public Common.Entities.ChannelAccessProfile channelaccessprofile_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.ChannelAccessProfile>("channelaccessprofile_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 channelaccessprofile_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("channelaccessprofile_DuplicateMatchingRecord")]
		public Common.Entities.ChannelAccessProfile channelaccessprofile_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.ChannelAccessProfile>("channelaccessprofile_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 characteristic_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("characteristic_DuplicateBaseRecord")]
		public Common.Entities.Characteristic characteristic_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Characteristic>("characteristic_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 characteristic_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("characteristic_DuplicateMatchingRecord")]
		public Common.Entities.Characteristic characteristic_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Characteristic>("characteristic_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Competitor_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Competitor_DuplicateBaseRecord")]
		public Common.Entities.Competitor Competitor_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Competitor>("Competitor_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Competitor_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Competitor_DuplicateMatchingRecord")]
		public Common.Entities.Competitor Competitor_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Competitor>("Competitor_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Contact_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contact_DuplicateBaseRecord")]
		public Common.Entities.Contact Contact_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Contact>("Contact_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Contact_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contact_DuplicateMatchingRecord")]
		public Common.Entities.Contact Contact_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Contact>("Contact_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Contract_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contract_DuplicateBaseRecord")]
		public Common.Entities.Contract Contract_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Contract>("Contract_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Contract_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contract_DuplicateMatchingRecord")]
		public Common.Entities.Contract Contract_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Contract>("Contract_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 DuplicateRule_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicateruleid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("DuplicateRule_DuplicateBaseRecord")]
		public Common.Entities.DuplicateRule DuplicateRule_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.DuplicateRule>("DuplicateRule_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Email_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Email_DuplicateBaseRecord")]
		public Common.Entities.Email Email_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Email>("Email_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Email_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Email_DuplicateMatchingRecord")]
		public Common.Entities.Email Email_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Email>("Email_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 emailserverprofile_duplicatebaserecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("emailserverprofile_duplicatebaserecord")]
		public Common.Entities.EmailServerProfile emailserverprofile_duplicatebaserecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.EmailServerProfile>("emailserverprofile_duplicatebaserecord", null);
			}
		}
		
		/// <summary>
		/// N:1 emailserverprofile_duplicatematchingrecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("emailserverprofile_duplicatematchingrecord")]
		public Common.Entities.EmailServerProfile emailserverprofile_duplicatematchingrecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.EmailServerProfile>("emailserverprofile_duplicatematchingrecord", null);
			}
		}
		
		/// <summary>
		/// N:1 entitlement_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlement_DuplicateBaseRecord")]
		public Common.Entities.Entitlement entitlement_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Entitlement>("entitlement_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 entitlement_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlement_DuplicateMatchingRecord")]
		public Common.Entities.Entitlement entitlement_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Entitlement>("entitlement_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 entitlementchannel_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementchannel_DuplicateBaseRecord")]
		public Common.Entities.EntitlementChannel entitlementchannel_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.EntitlementChannel>("entitlementchannel_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 entitlementchannel_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementchannel_DuplicateMatchingRecord")]
		public Common.Entities.EntitlementChannel entitlementchannel_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.EntitlementChannel>("entitlementchannel_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 entitlementtemplate_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_DuplicateBaseRecord")]
		public Common.Entities.EntitlementTemplate entitlementtemplate_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.EntitlementTemplate>("entitlementtemplate_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 entitlementtemplate_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_DuplicateMatchingRecord")]
		public Common.Entities.EntitlementTemplate entitlementtemplate_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.EntitlementTemplate>("entitlementtemplate_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Equipment_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Equipment_DuplicateBaseRecord")]
		public Common.Entities.Equipment Equipment_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Equipment>("Equipment_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Equipment_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Equipment_DuplicateMatchingRecord")]
		public Common.Entities.Equipment Equipment_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Equipment>("Equipment_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Fax_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Fax_DuplicateBaseRecord")]
		public Common.Entities.Fax Fax_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Fax>("Fax_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Fax_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Fax_DuplicateMatchingRecord")]
		public Common.Entities.Fax Fax_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Fax>("Fax_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Goal_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Goal_DuplicateBaseRecord")]
		public Common.Entities.Goal Goal_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Goal>("Goal_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Goal_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Goal_DuplicateMatchingRecord")]
		public Common.Entities.Goal Goal_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Goal>("Goal_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 GoalRollupQuery_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("GoalRollupQuery_DuplicateBaseRecord")]
		public Common.Entities.GoalRollupQuery GoalRollupQuery_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.GoalRollupQuery>("GoalRollupQuery_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 GoalRollupQuery_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("GoalRollupQuery_DuplicateMatchingRecord")]
		public Common.Entities.GoalRollupQuery GoalRollupQuery_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.GoalRollupQuery>("GoalRollupQuery_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Incident_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Incident_DuplicateBaseRecord")]
		public Common.Entities.Incident Incident_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Incident>("Incident_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Incident_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Incident_DuplicateMatchingRecord")]
		public Common.Entities.Incident Incident_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Incident>("Incident_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 KbArticle_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KbArticle_DuplicateBaseRecord")]
		public Common.Entities.KbArticle KbArticle_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.KbArticle>("KbArticle_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 KbArticle_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KbArticle_DuplicateMatchingRecord")]
		public Common.Entities.KbArticle KbArticle_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.KbArticle>("KbArticle_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 knowledgearticle_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_DuplicateBaseRecord")]
		public Common.Entities.KnowledgeArticle knowledgearticle_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.KnowledgeArticle>("knowledgearticle_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 knowledgearticle_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_DuplicateMatchingRecord")]
		public Common.Entities.KnowledgeArticle knowledgearticle_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.KnowledgeArticle>("knowledgearticle_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 KnowledgeBaseRecord_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_DuplicateBaseRecord")]
		public Common.Entities.KnowledgeBaseRecord KnowledgeBaseRecord_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.KnowledgeBaseRecord>("KnowledgeBaseRecord_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 KnowledgeBaseRecord_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_DuplicateMatchingRecord")]
		public Common.Entities.KnowledgeBaseRecord KnowledgeBaseRecord_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.KnowledgeBaseRecord>("KnowledgeBaseRecord_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Lead_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Lead_DuplicateBaseRecord")]
		public Common.Entities.Lead Lead_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Lead>("Lead_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Lead_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Lead_DuplicateMatchingRecord")]
		public Common.Entities.Lead Lead_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Lead>("Lead_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Letter_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Letter_DuplicateBaseRecord")]
		public Common.Entities.Letter Letter_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Letter>("Letter_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Letter_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Letter_DuplicateMatchingRecord")]
		public Common.Entities.Letter Letter_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Letter>("Letter_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 List_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("List_DuplicateBaseRecord")]
		public Common.Entities.List List_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.List>("List_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 List_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("List_DuplicateMatchingRecord")]
		public Common.Entities.List List_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.List>("List_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 msdyn_postalbum_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_postalbum_DuplicateBaseRecord")]
		public Common.Entities.msdyn_PostAlbum msdyn_postalbum_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.msdyn_PostAlbum>("msdyn_postalbum_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 msdyn_postalbum_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_postalbum_DuplicateMatchingRecord")]
		public Common.Entities.msdyn_PostAlbum msdyn_postalbum_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.msdyn_PostAlbum>("msdyn_postalbum_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 msdyn_relationshipinsightsunifiedconfig_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_relationshipinsightsunifiedconfig_DuplicateBaseRecord")]
		public Common.Entities.msdyn_relationshipinsightsunifiedconfig msdyn_relationshipinsightsunifiedconfig_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.msdyn_relationshipinsightsunifiedconfig>("msdyn_relationshipinsightsunifiedconfig_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 msdyn_relationshipinsightsunifiedconfig_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_relationshipinsightsunifiedconfig_DuplicateMatchingRecord")]
		public Common.Entities.msdyn_relationshipinsightsunifiedconfig msdyn_relationshipinsightsunifiedconfig_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.msdyn_relationshipinsightsunifiedconfig>("msdyn_relationshipinsightsunifiedconfig_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 msdyn_siconfig_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_siconfig_DuplicateBaseRecord")]
		public Common.Entities.msdyn_siconfig msdyn_siconfig_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.msdyn_siconfig>("msdyn_siconfig_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 msdyn_siconfig_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_siconfig_DuplicateMatchingRecord")]
		public Common.Entities.msdyn_siconfig msdyn_siconfig_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.msdyn_siconfig>("msdyn_siconfig_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Opportunity_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Opportunity_DuplicateBaseRecord")]
		public Common.Entities.Opportunity Opportunity_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Opportunity>("Opportunity_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Opportunity_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Opportunity_DuplicateMatchingRecord")]
		public Common.Entities.Opportunity Opportunity_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Opportunity>("Opportunity_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 PhoneCall_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("PhoneCall_DuplicateBaseRecord")]
		public Common.Entities.PhoneCall PhoneCall_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.PhoneCall>("PhoneCall_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 PhoneCall_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("PhoneCall_DuplicateMatchingRecord")]
		public Common.Entities.PhoneCall PhoneCall_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.PhoneCall>("PhoneCall_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Publisher_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Publisher_DuplicateBaseRecord")]
		public Common.Entities.Publisher Publisher_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Publisher>("Publisher_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Publisher_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Publisher_DuplicateMatchingRecord")]
		public Common.Entities.Publisher Publisher_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Publisher>("Publisher_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Queue_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Queue_DuplicateBaseRecord")]
		public Common.Entities.Queue Queue_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Queue>("Queue_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Queue_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Queue_DuplicateMatchingRecord")]
		public Common.Entities.Queue Queue_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Queue>("Queue_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Quote_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Quote_DuplicateBaseRecord")]
		public Common.Entities.Quote Quote_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Quote>("Quote_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Quote_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Quote_DuplicateMatchingRecord")]
		public Common.Entities.Quote Quote_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Quote>("Quote_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 ratingmodel_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ratingmodel_DuplicateBaseRecord")]
		public Common.Entities.RatingModel ratingmodel_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.RatingModel>("ratingmodel_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 ratingmodel_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ratingmodel_DuplicateMatchingRecord")]
		public Common.Entities.RatingModel ratingmodel_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.RatingModel>("ratingmodel_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 ratingvalue_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ratingvalue_DuplicateBaseRecord")]
		public Common.Entities.RatingValue ratingvalue_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.RatingValue>("ratingvalue_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 ratingvalue_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ratingvalue_DuplicateMatchingRecord")]
		public Common.Entities.RatingValue ratingvalue_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.RatingValue>("ratingvalue_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 RecurringAppointmentMaster_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("RecurringAppointmentMaster_DuplicateBaseRecord")]
		public Common.Entities.RecurringAppointmentMaster RecurringAppointmentMaster_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.RecurringAppointmentMaster>("RecurringAppointmentMaster_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 RecurringAppointmentMaster_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("RecurringAppointmentMaster_DuplicateMatchingRecord")]
		public Common.Entities.RecurringAppointmentMaster RecurringAppointmentMaster_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.RecurringAppointmentMaster>("RecurringAppointmentMaster_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 ResourceGroup_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ResourceGroup_DuplicateBaseRecord")]
		public Common.Entities.ResourceGroup ResourceGroup_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.ResourceGroup>("ResourceGroup_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 ResourceGroup_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ResourceGroup_DuplicateMatchingRecord")]
		public Common.Entities.ResourceGroup ResourceGroup_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.ResourceGroup>("ResourceGroup_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Service_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Service_DuplicateBaseRecord")]
		public Common.Entities.Service Service_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Service>("Service_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Service_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Service_DuplicateMatchingRecord")]
		public Common.Entities.Service Service_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Service>("Service_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SharePointDocumentLocation_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SharePointDocumentLocation_DuplicateBaseRecord")]
		public Common.Entities.SharePointDocumentLocation SharePointDocumentLocation_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SharePointDocumentLocation>("SharePointDocumentLocation_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SharePointDocumentLocation_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SharePointDocumentLocation_DuplicateMatchingRecord")]
		public Common.Entities.SharePointDocumentLocation SharePointDocumentLocation_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SharePointDocumentLocation>("SharePointDocumentLocation_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SharePointSite_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SharePointSite_DuplicateBaseRecord")]
		public Common.Entities.SharePointSite SharePointSite_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SharePointSite>("SharePointSite_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SharePointSite_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SharePointSite_DuplicateMatchingRecord")]
		public Common.Entities.SharePointSite SharePointSite_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SharePointSite>("SharePointSite_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SocialActivity_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SocialActivity_DuplicateBaseRecord")]
		public Common.Entities.SocialActivity SocialActivity_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SocialActivity>("SocialActivity_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SocialActivity_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SocialActivity_DuplicateMatchingRecord")]
		public Common.Entities.SocialActivity SocialActivity_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SocialActivity>("SocialActivity_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SocialProfile_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SocialProfile_DuplicateBaseRecord")]
		public Common.Entities.SocialProfile SocialProfile_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SocialProfile>("SocialProfile_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SocialProfile_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SocialProfile_DuplicateMatchingRecord")]
		public Common.Entities.SocialProfile SocialProfile_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SocialProfile>("SocialProfile_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SystemUser_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SystemUser_DuplicateBaseRecord")]
		public Common.Entities.SystemUser SystemUser_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SystemUser>("SystemUser_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 SystemUser_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SystemUser_DuplicateMatchingRecord")]
		public Common.Entities.SystemUser SystemUser_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.SystemUser>("SystemUser_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Task_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Task_DuplicateBaseRecord")]
		public Common.Entities.Task Task_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Task>("Task_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Task_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Task_DuplicateMatchingRecord")]
		public Common.Entities.Task Task_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Task>("Task_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Team_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Team_DuplicateBaseRecord")]
		public Common.Entities.Team Team_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Team>("Team_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Team_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Team_DuplicateMatchingRecord")]
		public Common.Entities.Team Team_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Team>("Team_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Territory_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Territory_DuplicateBaseRecord")]
		public Common.Entities.Territory Territory_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Territory>("Territory_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 Territory_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Territory_DuplicateMatchingRecord")]
		public Common.Entities.Territory Territory_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.Territory>("Territory_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baserecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_DuplicateBaseRecord")]
		public Common.Entities.TransactionCurrency TransactionCurrency_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.TransactionCurrency>("TransactionCurrency_DuplicateBaseRecord", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duplicaterecordid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_DuplicateMatchingRecord")]
		public Common.Entities.TransactionCurrency TransactionCurrency_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Common.Entities.TransactionCurrency>("TransactionCurrency_DuplicateMatchingRecord", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public DuplicateRecord(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["duplicateid"] = base.Id;
                        break;
                    case "duplicateid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}